"""Add latitude and longitude to properties

Revision ID: dcb69066ad8b
Revises: 06ea05c72164
Create Date: 2025-06-03 17:58:17.506150

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "dcb69066ad8b"
down_revision: Union[str, None] = "06ea05c72164"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("properties", sa.Column("latitude", sa.Float(), nullable=True))
    op.add_column("properties", sa.Column("longitude", sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("properties", "longitude")
    op.drop_column("properties", "latitude")
    # ### end Alembic commands ###
