"""Add city_id foreign key to properties

Revision ID: 20d80736030d
Revises: f3af72ee5fef
Create Date: 2025-06-04 12:14:06.815376

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "20d80736030d"
down_revision: Union[str, None] = "f3af72ee5fef"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("properties", sa.Column("city_id", sa.UUID(), nullable=True))
    op.create_foreign_key(None, "properties", "cities", ["city_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "properties", type_="foreignkey")
    op.drop_column("properties", "city_id")
    # ### end Alembic commands ###
