"""Add min max initial maintenance expenses to projects

Revision ID: a78e15676477
Revises: 9a12d960aa3d
Create Date: 2025-07-05 00:01:31.634940

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a78e15676477"
down_revision: Union[str, None] = "9a12d960aa3d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "projects",
        sa.Column(
            "min_initial_maintenance_expenses",
            sa.Numeric(precision=12, scale=2),
            nullable=True,
        ),
    )
    op.add_column(
        "projects",
        sa.Column(
            "max_initial_maintenance_expenses",
            sa.Numeric(precision=12, scale=2),
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("projects", "max_initial_maintenance_expenses")
    op.drop_column("projects", "min_initial_maintenance_expenses")
    # ### end Alembic commands ###
