"""Drop deprecated preset columns from expose links

Revision ID: f0e38007a1ea
Revises: 31b5ceb8e19c
Create Date: 2025-06-13 14:28:16.829486

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f0e38007a1ea"
down_revision: Union[str, None] = "31b5ceb8e19c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Drop deprecated columns
    op.drop_column('expose_links', 'preset_equity_amount')
    op.drop_column('expose_links', 'preset_loan_term_years')
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Re-add the columns if rolling back
    op.add_column('expose_links', sa.Column('preset_loan_term_years', sa.Integer(), nullable=True))
    op.add_column('expose_links', sa.Column('preset_equity_amount', sa.Numeric(precision=10, scale=2), nullable=True))
    
    # ### end Alembic commands ###
