"""Add provision percentage fields to users, teams and projects

Revision ID: 397e7e82ac1e
Revises: 2696d2ce6ada
Create Date: 2025-07-03 17:40:33.540393

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "397e7e82ac1e"
down_revision: Union[str, None] = "2696d2ce6ada"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add columns with nullable=True first
    op.add_column(
        "projects", sa.Column("provision_percentage", sa.Float(), nullable=True)
    )
    op.add_column(
        "user_team_assignments",
        sa.Column(
            "provision_percentage", sa.Integer(), nullable=True
        ),
    )
    op.add_column(
        "users", sa.Column("provision_percentage", sa.Integer(), nullable=True)
    )
    
    # Set default values for existing rows
    op.execute("UPDATE projects SET provision_percentage = 0.0 WHERE provision_percentage IS NULL")
    op.execute("UPDATE user_team_assignments SET provision_percentage = 0 WHERE provision_percentage IS NULL")
    op.execute("UPDATE users SET provision_percentage = 0 WHERE provision_percentage IS NULL")
    
    # Now make columns non-nullable
    op.alter_column("projects", "provision_percentage", nullable=False)
    op.alter_column("user_team_assignments", "provision_percentage", nullable=False, server_default="0")
    op.alter_column("users", "provision_percentage", nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "provision_percentage")
    op.drop_column("user_team_assignments", "provision_percentage")
    op.drop_column("projects", "provision_percentage")
    # ### end Alembic commands ###
