"""Remove display_order from city_images table

Revision ID: cff140843de7
Revises: 39cbc853c254
Create Date: 2025-07-11 11:34:09.390810

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "cff140843de7"
down_revision: Union[str, None] = "39cbc853c254"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("city_images", "display_order")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "city_images",
        sa.Column("display_order", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    # ### end Alembic commands ###
