"""Merge balcony and balcony_orientation into single field

Revision ID: 256bb0e369e4
Revises: 93726256601d
Create Date: 2025-07-13 12:11:34.075956

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "256bb0e369e4"
down_revision: Union[str, None] = "93726256601d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "properties",
        "balcony",
        existing_type=sa.BOOLEAN(),
        type_=sa.String(length=50),
        existing_nullable=True,
    )
    op.drop_column("properties", "balcony_orientation")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "properties",
        sa.Column(
            "balcony_orientation",
            sa.VARCHAR(length=50),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.alter_column(
        "properties",
        "balcony",
        existing_type=sa.String(length=50),
        type_=sa.BOOLEAN(),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
