"""add_investagon_id_to_projects

Revision ID: 43564f7330cc
Revises: add_project_permissions
Create Date: 2025-06-08 10:12:54.800478

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "43564f7330cc"
down_revision: Union[str, None] = "add_project_permissions"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "projects", sa.Column("investagon_id", sa.String(length=255), nullable=True)
    )
    op.add_column("projects", sa.Column("investagon_data", sa.JSON(), nullable=True))
    op.create_unique_constraint(None, "projects", ["investagon_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "projects", type_="unique")
    op.drop_column("projects", "investagon_data")
    op.drop_column("projects", "investagon_id")
    # ### end Alembic commands ###
