"""Remove deprecated transaction rate fields

Revision ID: cf9e0d114e69
Revises: 996a0eb9a24b
Create Date: 2025-07-14 00:50:50.185416

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "cf9e0d114e69"
down_revision: Union[str, None] = "996a0eb9a24b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("properties", "transaction_tax_rate")
    op.drop_column("properties", "transaction_broker_rate")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "properties",
        sa.Column(
            "transaction_broker_rate",
            sa.NUMERIC(precision=5, scale=2),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "properties",
        sa.Column(
            "transaction_tax_rate",
            sa.NUMERIC(precision=5, scale=2),
            autoincrement=False,
            nullable=True,
        ),
    )
    # ### end Alembic commands ###
