"""Add micro_location field to projects table

Revision ID: 6ffdb74a4890
Revises: 393d1b0d3929
Create Date: 2025-06-12 13:26:40.348477

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "6ffdb74a4890"
down_revision: Union[str, None] = "393d1b0d3929"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("projects", sa.Column("micro_location", sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("projects", "micro_location")
    # ### end Alembic commands ###
