"""Add highlights field to expose templates

Revision ID: 3a3f6adc7ad6
Revises: cf9e0d114e69
Create Date: 2025-07-15 14:13:57.500557

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "3a3f6adc7ad6"
down_revision: Union[str, None] = "cf9e0d114e69"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("expose_templates", sa.Column("highlights", sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("expose_templates", "highlights")
    # ### end Alembic commands ###
