"""remove_apartment_number_from_properties

Revision ID: b070c46651ca
Revises: 43564f7330cc
Create Date: 2025-06-08 16:01:33.952243

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b070c46651ca"
down_revision: Union[str, None] = "43564f7330cc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("properties", "apartment_number")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "properties",
        sa.Column(
            "apartment_number",
            sa.VARCHAR(length=100),
            autoincrement=False,
            nullable=True,
        ),
    )
    # ### end Alembic commands ###
