"""Add property fields: object_share, land_share, usage, maintenance, depreciation

Revision ID: 391a02dec3bb
Revises: 20d80736030d
Create Date: 2025-06-05 09:23:42.276538

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "391a02dec3bb"
down_revision: Union[str, None] = "20d80736030d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "properties", sa.Column("object_share_owner", sa.Float(), nullable=True)
    )
    op.add_column("properties", sa.Column("share_land", sa.Float(), nullable=True))
    op.add_column(
        "properties", sa.Column("property_usage", sa.String(length=100), nullable=True)
    )
    op.add_column(
        "properties",
        sa.Column(
            "initial_maintenance_expenses",
            sa.Numeric(precision=10, scale=2),
            nullable=True,
        ),
    )
    op.add_column(
        "properties",
        sa.Column(
            "degressive_depreciation_building_onoff", sa.Integer(), nullable=True
        ),
    )
    op.add_column(
        "properties",
        sa.Column("depreciation_rate_building_manual", sa.Float(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("properties", "depreciation_rate_building_manual")
    op.drop_column("properties", "degressive_depreciation_building_onoff")
    op.drop_column("properties", "initial_maintenance_expenses")
    op.drop_column("properties", "property_usage")
    op.drop_column("properties", "share_land")
    op.drop_column("properties", "object_share_owner")
    # ### end Alembic commands ###
