"""Add balcony field to properties

Revision ID: ba638777b64d
Revises: fa8c54dcf550
Create Date: 2025-06-11 11:03:54.395711

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ba638777b64d"
down_revision: Union[str, None] = "fa8c54dcf550"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("properties", sa.Column("balcony", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("properties", "balcony")
    # ### end Alembic commands ###
