"""Add color fields to tenant model

Revision ID: db8a86b8b05a
Revises: 1e2a45e51243
Create Date: 2025-07-18 14:04:16.421246

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "db8a86b8b05a"
down_revision: Union[str, None] = "1e2a45e51243"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "tenants", sa.Column("primary_color", sa.String(length=7), nullable=True)
    )
    op.add_column(
        "tenants", sa.Column("secondary_color", sa.String(length=7), nullable=True)
    )
    op.add_column(
        "tenants", sa.Column("accent_color", sa.String(length=7), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tenants", "accent_color")
    op.drop_column("tenants", "secondary_color")
    op.drop_column("tenants", "primary_color")
    # ### end Alembic commands ###
