"""add_investagon_credentials_to_tenant

Revision ID: ed00dba37ca7
Revises: fa2eab385270
Create Date: 2025-06-06 16:07:24.854058

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ed00dba37ca7"
down_revision: Union[str, None] = "fa2eab385270"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "tenants",
        sa.Column("investagon_organization_id", sa.String(length=255), nullable=True),
    )
    op.add_column(
        "tenants", sa.Column("investagon_api_key", sa.String(length=255), nullable=True)
    )
    # Add column as nullable first
    op.add_column(
        "tenants", sa.Column("investagon_sync_enabled", sa.Boolean(), nullable=True)
    )
    # Set default value for existing rows
    op.execute("UPDATE tenants SET investagon_sync_enabled = false")
    # Make it non-nullable
    op.alter_column("tenants", "investagon_sync_enabled", nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tenants", "investagon_sync_enabled")
    op.drop_column("tenants", "investagon_api_key")
    op.drop_column("tenants", "investagon_organization_id")
    # ### end Alembic commands ###
