"""Update project status values to match property statuses

Revision ID: 430449afd390
Revises: b070c46651ca
Create Date: 2025-06-08 23:41:44.214976

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "430449afd390"
down_revision: Union[str, None] = "b070c46651ca"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Update existing project statuses to match property status values
    op.execute("""
        UPDATE projects 
        SET status = CASE 
            WHEN status = 'active' THEN 'available'
            WHEN status = 'planned' THEN 'reserved'
            WHEN status = 'completed' THEN 'sold'
            ELSE status
        END
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Revert project statuses back to original values
    op.execute("""
        UPDATE projects 
        SET status = CASE 
            WHEN status = 'available' THEN 'active'
            WHEN status = 'reserved' THEN 'planned'
            WHEN status = 'sold' THEN 'completed'
            ELSE status
        END
    """)
    # ### end Alembic commands ###
