"""Refactor expose links to use preset_data JSON field

Revision ID: 032f59326212
Revises: db8a86b8b05a
Create Date: 2025-07-22 00:15:36.645026

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "032f59326212"
down_revision: Union[str, None] = "db8a86b8b05a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("expose_links", sa.Column("preset_data", sa.JSON(), nullable=True))
    op.drop_column("expose_links", "preset_repayment_rate")
    op.drop_column("expose_links", "preset_is_married")
    op.drop_column("expose_links", "visible_sections")
    op.drop_column("expose_links", "preset_interest_rate")
    op.drop_column("expose_links", "preset_monthly_rent")
    op.drop_column("expose_links", "preset_equity_percentage")
    op.drop_column("expose_links", "preset_gross_income")
    op.drop_column("expose_links", "custom_message")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "expose_links",
        sa.Column("custom_message", sa.TEXT(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "expose_links",
        sa.Column(
            "preset_gross_income",
            sa.NUMERIC(precision=10, scale=2),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "expose_links",
        sa.Column(
            "preset_equity_percentage",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "expose_links",
        sa.Column(
            "preset_monthly_rent",
            sa.NUMERIC(precision=10, scale=2),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "expose_links",
        sa.Column(
            "preset_interest_rate",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "expose_links",
        sa.Column(
            "visible_sections",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "expose_links",
        sa.Column(
            "preset_is_married", sa.BOOLEAN(), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "expose_links",
        sa.Column(
            "preset_repayment_rate",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_column("expose_links", "preset_data")
    # ### end Alembic commands ###
