"""Add primary_energy_consumption to properties

Revision ID: de2bd1ce89aa
Revises: 83c1ae19fcea
Create Date: 2025-06-11 11:43:04.579189

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "de2bd1ce89aa"
down_revision: Union[str, None] = "83c1ae19fcea"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "properties", sa.Column("primary_energy_consumption", sa.Float(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("properties", "primary_energy_consumption")
    # ### end Alembic commands ###
