"""Change floor field from Integer to String in properties

Revision ID: 83c1ae19fcea
Revises: ba638777b64d
Create Date: 2025-06-11 11:12:05.171789

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "83c1ae19fcea"
down_revision: Union[str, None] = "ba638777b64d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # PostgreSQL requires explicit casting when changing from INTEGER to VARCHAR
    op.execute("ALTER TABLE properties ALTER COLUMN floor TYPE VARCHAR(50) USING floor::VARCHAR")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # For downgrade, we need to handle potential non-numeric values
    # This will convert any non-numeric values to NULL
    op.execute("""
        ALTER TABLE properties 
        ALTER COLUMN floor TYPE INTEGER 
        USING CASE 
            WHEN floor ~ '^[0-9]+$' THEN floor::INTEGER 
            ELSE NULL 
        END
    """)
    # ### end Alembic commands ###
