"""Add new fields for issues 50 and 51

Revision ID: 93726256601d
Revises: b3713fe9b17f
Create Date: 2025-07-13 10:54:32.463793

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "93726256601d"
down_revision: Union[str, None] = "b3713fe9b17f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "projects", sa.Column("backyard_development", sa.Boolean(), nullable=True)
    )
    op.add_column(
        "projects", sa.Column("sev_takeover_one_year", sa.Boolean(), nullable=True)
    )
    op.add_column("projects", sa.Column("renovations", sa.JSON(), nullable=True))
    op.add_column(
        "properties",
        sa.Column("reserves", sa.Numeric(precision=10, scale=2), nullable=True),
    )
    op.add_column(
        "properties",
        sa.Column("balcony_orientation", sa.String(length=50), nullable=True),
    )
    op.add_column(
        "properties",
        sa.Column("takeover_special_charges_years", sa.Integer(), nullable=True),
    )
    op.add_column(
        "properties",
        sa.Column(
            "takeover_special_charges_amount",
            sa.Numeric(precision=10, scale=2),
            nullable=True,
        ),
    )
    op.add_column("properties", sa.Column("has_cellar", sa.Boolean(), nullable=True))
    op.add_column(
        "properties", sa.Column("parking_type", sa.String(length=50), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("properties", "parking_type")
    op.drop_column("properties", "has_cellar")
    op.drop_column("properties", "takeover_special_charges_amount")
    op.drop_column("properties", "takeover_special_charges_years")
    op.drop_column("properties", "balcony_orientation")
    op.drop_column("properties", "reserves")
    op.drop_column("projects", "renovations")
    op.drop_column("projects", "sev_takeover_one_year")
    op.drop_column("projects", "backyard_development")
    # ### end Alembic commands ###
