"""Add new preset fields to expose links

Revision ID: 31b5ceb8e19c
Revises: e62769cc8c35
Create Date: 2025-06-13 14:06:34.624605

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "31b5ceb8e19c"
down_revision: Union[str, None] = "e62769cc8c35"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Add new fields to expose_links table
    op.add_column('expose_links', sa.Column('preset_equity_percentage', sa.Float(), nullable=True))
    op.add_column('expose_links', sa.Column('preset_repayment_rate', sa.Float(), nullable=True))
    op.add_column('expose_links', sa.Column('preset_gross_income', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('expose_links', sa.Column('preset_is_married', sa.Boolean(), nullable=True))
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Remove the new fields
    op.drop_column('expose_links', 'preset_is_married')
    op.drop_column('expose_links', 'preset_gross_income')
    op.drop_column('expose_links', 'preset_repayment_rate')
    op.drop_column('expose_links', 'preset_equity_percentage')
    
    # ### end Alembic commands ###
