"""Refactor ExposeTemplate to support structured content sections

Revision ID: 9db411757f96
Revises: 5029ce443c42
Create Date: 2025-07-07 21:07:03.574326

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "9db411757f96"
down_revision: Union[str, None] = "5029ce443c42"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add enabled_sections with default value for existing rows
    op.add_column(
        "expose_templates", sa.Column("enabled_sections", sa.JSON(), nullable=True)
    )
    # Set default value for existing rows
    op.execute("""
        UPDATE expose_templates 
        SET enabled_sections = '{
            "hero": true,
            "city_info": true,
            "micro_location": true,
            "property_data": true,
            "floor_plan": true,
            "modernization": true,
            "financial": true,
            "insurance": true,
            "process_steps": true,
            "opportunities_risks": true,
            "contact": true
        }'::jsonb
        WHERE enabled_sections IS NULL
    """)
    # Now make it non-nullable
    op.alter_column("expose_templates", "enabled_sections", nullable=False)
    op.add_column(
        "expose_templates", sa.Column("floor_plan_content", sa.Text(), nullable=True)
    )
    op.add_column(
        "expose_templates", sa.Column("modernization_items", sa.JSON(), nullable=True)
    )
    op.add_column(
        "expose_templates", sa.Column("insurance_plans", sa.JSON(), nullable=True)
    )
    op.add_column(
        "expose_templates", sa.Column("process_steps_list", sa.JSON(), nullable=True)
    )
    op.add_column(
        "expose_templates", sa.Column("opportunities_list", sa.JSON(), nullable=True)
    )
    op.add_column("expose_templates", sa.Column("risks_list", sa.JSON(), nullable=True))
    op.drop_column("expose_templates", "default_equity_percentage")
    op.drop_column("expose_templates", "is_active")
    op.drop_column("expose_templates", "name")
    op.drop_column("expose_templates", "company_info")
    op.drop_column("expose_templates", "default_tax_rate")
    op.drop_column("expose_templates", "default_loan_term_years")
    op.drop_column("expose_templates", "risks_disclaimer")
    op.drop_column("expose_templates", "property_description")
    op.drop_column("expose_templates", "investment_benefits")
    op.drop_column("expose_templates", "property_type")
    op.drop_column("expose_templates", "is_default")
    op.drop_column("expose_templates", "location_description")
    op.drop_column("expose_templates", "process_steps")
    op.drop_column("expose_templates", "financing_info")
    op.drop_column("expose_templates", "default_interest_rate")
    op.drop_column("expose_templates", "tax_benefits")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "expose_templates",
        sa.Column("tax_benefits", sa.TEXT(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "expose_templates",
        sa.Column(
            "default_interest_rate",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "expose_templates",
        sa.Column("financing_info", sa.TEXT(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "expose_templates",
        sa.Column("process_steps", sa.TEXT(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "expose_templates",
        sa.Column(
            "location_description", sa.TEXT(), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "expose_templates",
        sa.Column("is_default", sa.BOOLEAN(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "expose_templates",
        sa.Column(
            "property_type", sa.VARCHAR(length=100), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "expose_templates",
        sa.Column("investment_benefits", sa.TEXT(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "expose_templates",
        sa.Column(
            "property_description", sa.TEXT(), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "expose_templates",
        sa.Column("risks_disclaimer", sa.TEXT(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "expose_templates",
        sa.Column(
            "default_loan_term_years", sa.INTEGER(), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "expose_templates",
        sa.Column(
            "default_tax_rate",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "expose_templates",
        sa.Column("company_info", sa.TEXT(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "expose_templates",
        sa.Column("name", sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    )
    op.add_column(
        "expose_templates",
        sa.Column("is_active", sa.BOOLEAN(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "expose_templates",
        sa.Column(
            "default_equity_percentage",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_column("expose_templates", "risks_list")
    op.drop_column("expose_templates", "opportunities_list")
    op.drop_column("expose_templates", "process_steps_list")
    op.drop_column("expose_templates", "insurance_plans")
    op.drop_column("expose_templates", "modernization_items")
    op.drop_column("expose_templates", "floor_plan_content")
    op.drop_column("expose_templates", "enabled_sections")
    # ### end Alembic commands ###
