"""Add price and rental yield aggregates to projects

Revision ID: 390dc5350828
Revises: b7831082344d
Create Date: 2025-06-30 14:37:02.594367

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "390dc5350828"
down_revision: Union[str, None] = "b7831082344d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "projects",
        sa.Column("min_price", sa.Numeric(precision=12, scale=2), nullable=True),
    )
    op.add_column(
        "projects",
        sa.Column("max_price", sa.Numeric(precision=12, scale=2), nullable=True),
    )
    op.add_column(
        "projects",
        sa.Column("min_rental_yield", sa.Numeric(precision=5, scale=2), nullable=True),
    )
    op.add_column(
        "projects",
        sa.Column("max_rental_yield", sa.Numeric(precision=5, scale=2), nullable=True),
    )
    op.create_index("idx_projects_min_price", "projects", ["min_price"], unique=False)
    op.create_index(
        "idx_projects_min_rental_yield", "projects", ["min_rental_yield"], unique=False
    )
    # ### end Alembic commands ###
    
    # Populate the new columns with calculated values from existing properties
    op.execute("""
        UPDATE projects p
        SET 
            min_price = (
                SELECT MIN(purchase_price + COALESCE(purchase_price_parking, 0) + COALESCE(purchase_price_furniture, 0))
                FROM properties 
                WHERE project_id = p.id AND purchase_price IS NOT NULL
            ),
            max_price = (
                SELECT MAX(purchase_price + COALESCE(purchase_price_parking, 0) + COALESCE(purchase_price_furniture, 0))
                FROM properties 
                WHERE project_id = p.id AND purchase_price IS NOT NULL
            ),
            min_rental_yield = (
                SELECT MIN(
                    CASE 
                        WHEN purchase_price > 0 THEN 
                            ((monthly_rent + COALESCE(rent_parking_month, 0)) * 12 * 100.0) / 
                            (purchase_price + COALESCE(purchase_price_parking, 0) + COALESCE(purchase_price_furniture, 0))
                        ELSE NULL
                    END
                )
                FROM properties 
                WHERE project_id = p.id
            ),
            max_rental_yield = (
                SELECT MAX(
                    CASE 
                        WHEN purchase_price > 0 THEN 
                            ((monthly_rent + COALESCE(rent_parking_month, 0)) * 12 * 100.0) / 
                            (purchase_price + COALESCE(purchase_price_parking, 0) + COALESCE(purchase_price_furniture, 0))
                        ELSE NULL
                    END
                )
                FROM properties 
                WHERE project_id = p.id
            )
    """)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_projects_min_rental_yield", table_name="projects")
    op.drop_index("idx_projects_min_price", table_name="projects")
    op.drop_column("projects", "max_rental_yield")
    op.drop_column("projects", "min_rental_yield")
    op.drop_column("projects", "max_price")
    op.drop_column("projects", "min_price")
    # ### end Alembic commands ###
