"""Add primary_energy_consumption and heating_building_year to projects

Revision ID: a46b4c95dc98
Revises: de2bd1ce89aa
Create Date: 2025-06-11 20:18:57.211581

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a46b4c95dc98"
down_revision: Union[str, None] = "de2bd1ce89aa"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "projects", sa.Column("primary_energy_consumption", sa.Float(), nullable=True)
    )
    op.add_column(
        "projects", sa.Column("heating_building_year", sa.Integer(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("projects", "heating_building_year")
    op.drop_column("projects", "primary_energy_consumption")
    # ### end Alembic commands ###
